# Generated by Django 2.2.3 on 2020-09-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='emp_name')),
                ('salary', models.FloatField(verbose_name='emp_sal')),
                ('des', models.CharField(max_length=30, verbose_name='emp_des')),
                ('age', models.IntegerField(verbose_name='emp_age')),
                ('active', models.CharField(default='Y', max_length=30, verbose_name='active')),
            ],
        ),
    ]
